# Generated by Django 4.2.5 on 2026-02-28 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='emotions/')),
                ('text_input', models.TextField(blank=True, null=True)),
                ('emotion', models.CharField(max_length=50)),
                ('prediction_type', models.CharField(default='face', max_length=20)),
                ('face_confidence', models.FloatField(blank=True, null=True)),
                ('text_confidence', models.FloatField(blank=True, null=True)),
                ('combined_confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
