# Generated by Django 4.2.5 on 2026-02-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='combined_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='face_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotion_images/'),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='prediction_type',
            field=models.CharField(choices=[('face', 'Face Only'), ('text', 'Text Only'), ('multimodal', 'Face + Text')], default='face', max_length=20),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='text_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
