# Generated by Django 4.2.5 on 2026-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
