# Generated by Django 4.2.5 on 2026-02-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0002_alter_emotionresult_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotionresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emotionresult',
            name='combined_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotionresult',
            name='face_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotionresult',
            name='prediction_type',
            field=models.CharField(default='face', max_length=20),
        ),
        migrations.AddField(
            model_name='emotionresult',
            name='text_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emotionresult',
            name='text_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emotionresult',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='emotions/'),
        ),
    ]
